//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APAG___Aplikacija_za_alternativno_glasanje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glasanje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Glasanje()
        {
            this.Glasac = new HashSet<Glasac>();
            this.Kandidat = new HashSet<Kandidat>();
        }
    
        public int ID_glasanja { get; set; }
        public string Naziv { get; set; }
        public int AdministratorID_administrator { get; set; }
        public System.DateTime Datum { get; set; }
        public Nullable<bool> KorisnickoImeOdabir { get; set; }
        public Nullable<bool> OIBOdabir { get; set; }
        public Nullable<bool> BrojOsobneIskazniceOdabir { get; set; }
        public Nullable<bool> ImeOdabir { get; set; }
        public Nullable<bool> PrezimeOdabir { get; set; }
        public string Pobjednik { get; set; }
        public bool Završeno { get; set; }
        public System.TimeSpan VrijemePocetka { get; set; }
        public System.TimeSpan VrijemeZavrsetka { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Glasac> Glasac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kandidat> Kandidat { get; set; }
    }
}
