//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APAG___Aplikacija_za_alternativno_glasanje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Glas()
        {
            this.Kandidat = new HashSet<Kandidat>();
        }
    
        public int ID_glasa { get; set; }
        public System.TimeSpan Vrijeme { get; set; }
        public System.DateTime Datum { get; set; }
        public int GlasanjeID_glasanja { get; set; }
        public int KandidatGlasanjaID_glasanja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kandidat> Kandidat { get; set; }
    }
}
