//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APAG___Aplikacija_za_alternativno_glasanje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glasac
    {
        public int ID_glasac { get; set; }
        public int Tip_korisnikaID_tipa2 { get; set; }
        public string OIB { get; set; }
        public string Korsinicko_ime { get; set; }
        public string Lozinka { get; set; }
        public string Broj_osobne_iskaznice { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public bool Glasao { get; set; }
        public int ID_glasanja { get; set; }
    
        public virtual Glasanje Glasanje { get; set; }
        public virtual TipKorisnika TipKorisnika { get; set; }
    }
}
