//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APAG___Aplikacija_za_alternativno_glasanje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kandidat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kandidat()
        {
            this.Glas = new HashSet<Glas>();
        }
    
        public int ID_kandidata { get; set; }
        public int GlasanjeID_glasanja { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Naziv { get; set; }
        public string DodatnaPoruka { get; set; }
        public byte[] Slika { get; set; }
    
        public virtual Glasanje Glasanje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Glas> Glas { get; set; }
    }
}
